/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedCustomersRouteImport } from './routes/_protected/customers'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedCustomersIndexRouteImport } from './routes/_protected/customers/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedCustomersNewRouteImport } from './routes/_protected/customers/new'
import { Route as ProtectedCustomersCustomerIdRouteImport } from './routes/_protected/customers/$customerId'
import { Route as ProtectedConfiguratorCustomerIdRouteImport } from './routes/_protected/configurator/$customerId'
import { Route as ProtectedAdminProductConfigsRouteImport } from './routes/_protected/admin/product-configs'
import { Route as ProtectedAdminGridStylesRouteImport } from './routes/_protected/admin/grid-styles'
import { Route as ProtectedAdminGridSizesRouteImport } from './routes/_protected/admin/grid-sizes'
import { Route as ProtectedAdminGlassTypesRouteImport } from './routes/_protected/admin/glass-types'
import { Route as ProtectedAdminFrameTypesRouteImport } from './routes/_protected/admin/frame-types'
import { Route as ProtectedAdminFrameColorsRouteImport } from './routes/_protected/admin/frame-colors'
import { Route as ProtectedAdminDisclaimersRouteImport } from './routes/_protected/admin/disclaimers'
import { Route as ProtectedAdminBrandsRouteImport } from './routes/_protected/admin/brands'
import { Route as ProtectedCustomersCustomerIdIndexRouteImport } from './routes/_protected/customers/$customerId/index'
import { Route as ProtectedCustomersCustomerIdEstimateRouteImport } from './routes/_protected/customers/$customerId/estimate'
import { Route as ProtectedCustomersCustomerIdContractRouteImport } from './routes/_protected/customers/$customerId/contract'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCustomersRoute = ProtectedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersIndexRoute = ProtectedCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedCustomersRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedCustomersNewRoute = ProtectedCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedCustomersRoute,
} as any)
const ProtectedCustomersCustomerIdRoute =
  ProtectedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => ProtectedCustomersRoute,
  } as any)
const ProtectedConfiguratorCustomerIdRoute =
  ProtectedConfiguratorCustomerIdRouteImport.update({
    id: '/configurator/$customerId',
    path: '/configurator/$customerId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminProductConfigsRoute =
  ProtectedAdminProductConfigsRouteImport.update({
    id: '/product-configs',
    path: '/product-configs',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminGridStylesRoute =
  ProtectedAdminGridStylesRouteImport.update({
    id: '/grid-styles',
    path: '/grid-styles',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminGridSizesRoute = ProtectedAdminGridSizesRouteImport.update({
  id: '/grid-sizes',
  path: '/grid-sizes',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminGlassTypesRoute =
  ProtectedAdminGlassTypesRouteImport.update({
    id: '/glass-types',
    path: '/glass-types',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminFrameTypesRoute =
  ProtectedAdminFrameTypesRouteImport.update({
    id: '/frame-types',
    path: '/frame-types',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminFrameColorsRoute =
  ProtectedAdminFrameColorsRouteImport.update({
    id: '/frame-colors',
    path: '/frame-colors',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminDisclaimersRoute =
  ProtectedAdminDisclaimersRouteImport.update({
    id: '/disclaimers',
    path: '/disclaimers',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminBrandsRoute = ProtectedAdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedCustomersCustomerIdIndexRoute =
  ProtectedCustomersCustomerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedCustomersCustomerIdRoute,
  } as any)
const ProtectedCustomersCustomerIdEstimateRoute =
  ProtectedCustomersCustomerIdEstimateRouteImport.update({
    id: '/estimate',
    path: '/estimate',
    getParentRoute: () => ProtectedCustomersCustomerIdRoute,
  } as any)
const ProtectedCustomersCustomerIdContractRoute =
  ProtectedCustomersCustomerIdContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => ProtectedCustomersCustomerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/customers': typeof ProtectedCustomersRouteWithChildren
  '/admin/brands': typeof ProtectedAdminBrandsRoute
  '/admin/disclaimers': typeof ProtectedAdminDisclaimersRoute
  '/admin/frame-colors': typeof ProtectedAdminFrameColorsRoute
  '/admin/frame-types': typeof ProtectedAdminFrameTypesRoute
  '/admin/glass-types': typeof ProtectedAdminGlassTypesRoute
  '/admin/grid-sizes': typeof ProtectedAdminGridSizesRoute
  '/admin/grid-styles': typeof ProtectedAdminGridStylesRoute
  '/admin/product-configs': typeof ProtectedAdminProductConfigsRoute
  '/configurator/$customerId': typeof ProtectedConfiguratorCustomerIdRoute
  '/customers/$customerId': typeof ProtectedCustomersCustomerIdRouteWithChildren
  '/customers/new': typeof ProtectedCustomersNewRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/customers/': typeof ProtectedCustomersIndexRoute
  '/customers/$customerId/contract': typeof ProtectedCustomersCustomerIdContractRoute
  '/customers/$customerId/estimate': typeof ProtectedCustomersCustomerIdEstimateRoute
  '/customers/$customerId/': typeof ProtectedCustomersCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/brands': typeof ProtectedAdminBrandsRoute
  '/admin/disclaimers': typeof ProtectedAdminDisclaimersRoute
  '/admin/frame-colors': typeof ProtectedAdminFrameColorsRoute
  '/admin/frame-types': typeof ProtectedAdminFrameTypesRoute
  '/admin/glass-types': typeof ProtectedAdminGlassTypesRoute
  '/admin/grid-sizes': typeof ProtectedAdminGridSizesRoute
  '/admin/grid-styles': typeof ProtectedAdminGridStylesRoute
  '/admin/product-configs': typeof ProtectedAdminProductConfigsRoute
  '/configurator/$customerId': typeof ProtectedConfiguratorCustomerIdRoute
  '/customers/new': typeof ProtectedCustomersNewRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/customers': typeof ProtectedCustomersIndexRoute
  '/customers/$customerId/contract': typeof ProtectedCustomersCustomerIdContractRoute
  '/customers/$customerId/estimate': typeof ProtectedCustomersCustomerIdEstimateRoute
  '/customers/$customerId': typeof ProtectedCustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/customers': typeof ProtectedCustomersRouteWithChildren
  '/_protected/admin/brands': typeof ProtectedAdminBrandsRoute
  '/_protected/admin/disclaimers': typeof ProtectedAdminDisclaimersRoute
  '/_protected/admin/frame-colors': typeof ProtectedAdminFrameColorsRoute
  '/_protected/admin/frame-types': typeof ProtectedAdminFrameTypesRoute
  '/_protected/admin/glass-types': typeof ProtectedAdminGlassTypesRoute
  '/_protected/admin/grid-sizes': typeof ProtectedAdminGridSizesRoute
  '/_protected/admin/grid-styles': typeof ProtectedAdminGridStylesRoute
  '/_protected/admin/product-configs': typeof ProtectedAdminProductConfigsRoute
  '/_protected/configurator/$customerId': typeof ProtectedConfiguratorCustomerIdRoute
  '/_protected/customers/$customerId': typeof ProtectedCustomersCustomerIdRouteWithChildren
  '/_protected/customers/new': typeof ProtectedCustomersNewRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/customers/': typeof ProtectedCustomersIndexRoute
  '/_protected/customers/$customerId/contract': typeof ProtectedCustomersCustomerIdContractRoute
  '/_protected/customers/$customerId/estimate': typeof ProtectedCustomersCustomerIdEstimateRoute
  '/_protected/customers/$customerId/': typeof ProtectedCustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/customers'
    | '/admin/brands'
    | '/admin/disclaimers'
    | '/admin/frame-colors'
    | '/admin/frame-types'
    | '/admin/glass-types'
    | '/admin/grid-sizes'
    | '/admin/grid-styles'
    | '/admin/product-configs'
    | '/configurator/$customerId'
    | '/customers/$customerId'
    | '/customers/new'
    | '/admin/'
    | '/customers/'
    | '/customers/$customerId/contract'
    | '/customers/$customerId/estimate'
    | '/customers/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/brands'
    | '/admin/disclaimers'
    | '/admin/frame-colors'
    | '/admin/frame-types'
    | '/admin/glass-types'
    | '/admin/grid-sizes'
    | '/admin/grid-styles'
    | '/admin/product-configs'
    | '/configurator/$customerId'
    | '/customers/new'
    | '/admin'
    | '/customers'
    | '/customers/$customerId/contract'
    | '/customers/$customerId/estimate'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/admin'
    | '/_protected/customers'
    | '/_protected/admin/brands'
    | '/_protected/admin/disclaimers'
    | '/_protected/admin/frame-colors'
    | '/_protected/admin/frame-types'
    | '/_protected/admin/glass-types'
    | '/_protected/admin/grid-sizes'
    | '/_protected/admin/grid-styles'
    | '/_protected/admin/product-configs'
    | '/_protected/configurator/$customerId'
    | '/_protected/customers/$customerId'
    | '/_protected/customers/new'
    | '/_protected/admin/'
    | '/_protected/customers/'
    | '/_protected/customers/$customerId/contract'
    | '/_protected/customers/$customerId/estimate'
    | '/_protected/customers/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/customers': {
      id: '/_protected/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedCustomersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers/': {
      id: '/_protected/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof ProtectedCustomersIndexRouteImport
      parentRoute: typeof ProtectedCustomersRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/customers/new': {
      id: '/_protected/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof ProtectedCustomersNewRouteImport
      parentRoute: typeof ProtectedCustomersRoute
    }
    '/_protected/customers/$customerId': {
      id: '/_protected/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof ProtectedCustomersCustomerIdRouteImport
      parentRoute: typeof ProtectedCustomersRoute
    }
    '/_protected/configurator/$customerId': {
      id: '/_protected/configurator/$customerId'
      path: '/configurator/$customerId'
      fullPath: '/configurator/$customerId'
      preLoaderRoute: typeof ProtectedConfiguratorCustomerIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/product-configs': {
      id: '/_protected/admin/product-configs'
      path: '/product-configs'
      fullPath: '/admin/product-configs'
      preLoaderRoute: typeof ProtectedAdminProductConfigsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/grid-styles': {
      id: '/_protected/admin/grid-styles'
      path: '/grid-styles'
      fullPath: '/admin/grid-styles'
      preLoaderRoute: typeof ProtectedAdminGridStylesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/grid-sizes': {
      id: '/_protected/admin/grid-sizes'
      path: '/grid-sizes'
      fullPath: '/admin/grid-sizes'
      preLoaderRoute: typeof ProtectedAdminGridSizesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/glass-types': {
      id: '/_protected/admin/glass-types'
      path: '/glass-types'
      fullPath: '/admin/glass-types'
      preLoaderRoute: typeof ProtectedAdminGlassTypesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/frame-types': {
      id: '/_protected/admin/frame-types'
      path: '/frame-types'
      fullPath: '/admin/frame-types'
      preLoaderRoute: typeof ProtectedAdminFrameTypesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/frame-colors': {
      id: '/_protected/admin/frame-colors'
      path: '/frame-colors'
      fullPath: '/admin/frame-colors'
      preLoaderRoute: typeof ProtectedAdminFrameColorsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/disclaimers': {
      id: '/_protected/admin/disclaimers'
      path: '/disclaimers'
      fullPath: '/admin/disclaimers'
      preLoaderRoute: typeof ProtectedAdminDisclaimersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/brands': {
      id: '/_protected/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof ProtectedAdminBrandsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/customers/$customerId/': {
      id: '/_protected/customers/$customerId/'
      path: '/'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof ProtectedCustomersCustomerIdIndexRouteImport
      parentRoute: typeof ProtectedCustomersCustomerIdRoute
    }
    '/_protected/customers/$customerId/estimate': {
      id: '/_protected/customers/$customerId/estimate'
      path: '/estimate'
      fullPath: '/customers/$customerId/estimate'
      preLoaderRoute: typeof ProtectedCustomersCustomerIdEstimateRouteImport
      parentRoute: typeof ProtectedCustomersCustomerIdRoute
    }
    '/_protected/customers/$customerId/contract': {
      id: '/_protected/customers/$customerId/contract'
      path: '/contract'
      fullPath: '/customers/$customerId/contract'
      preLoaderRoute: typeof ProtectedCustomersCustomerIdContractRouteImport
      parentRoute: typeof ProtectedCustomersCustomerIdRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminBrandsRoute: typeof ProtectedAdminBrandsRoute
  ProtectedAdminDisclaimersRoute: typeof ProtectedAdminDisclaimersRoute
  ProtectedAdminFrameColorsRoute: typeof ProtectedAdminFrameColorsRoute
  ProtectedAdminFrameTypesRoute: typeof ProtectedAdminFrameTypesRoute
  ProtectedAdminGlassTypesRoute: typeof ProtectedAdminGlassTypesRoute
  ProtectedAdminGridSizesRoute: typeof ProtectedAdminGridSizesRoute
  ProtectedAdminGridStylesRoute: typeof ProtectedAdminGridStylesRoute
  ProtectedAdminProductConfigsRoute: typeof ProtectedAdminProductConfigsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminBrandsRoute: ProtectedAdminBrandsRoute,
  ProtectedAdminDisclaimersRoute: ProtectedAdminDisclaimersRoute,
  ProtectedAdminFrameColorsRoute: ProtectedAdminFrameColorsRoute,
  ProtectedAdminFrameTypesRoute: ProtectedAdminFrameTypesRoute,
  ProtectedAdminGlassTypesRoute: ProtectedAdminGlassTypesRoute,
  ProtectedAdminGridSizesRoute: ProtectedAdminGridSizesRoute,
  ProtectedAdminGridStylesRoute: ProtectedAdminGridStylesRoute,
  ProtectedAdminProductConfigsRoute: ProtectedAdminProductConfigsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedCustomersCustomerIdRouteChildren {
  ProtectedCustomersCustomerIdContractRoute: typeof ProtectedCustomersCustomerIdContractRoute
  ProtectedCustomersCustomerIdEstimateRoute: typeof ProtectedCustomersCustomerIdEstimateRoute
  ProtectedCustomersCustomerIdIndexRoute: typeof ProtectedCustomersCustomerIdIndexRoute
}

const ProtectedCustomersCustomerIdRouteChildren: ProtectedCustomersCustomerIdRouteChildren =
  {
    ProtectedCustomersCustomerIdContractRoute:
      ProtectedCustomersCustomerIdContractRoute,
    ProtectedCustomersCustomerIdEstimateRoute:
      ProtectedCustomersCustomerIdEstimateRoute,
    ProtectedCustomersCustomerIdIndexRoute:
      ProtectedCustomersCustomerIdIndexRoute,
  }

const ProtectedCustomersCustomerIdRouteWithChildren =
  ProtectedCustomersCustomerIdRoute._addFileChildren(
    ProtectedCustomersCustomerIdRouteChildren,
  )

interface ProtectedCustomersRouteChildren {
  ProtectedCustomersCustomerIdRoute: typeof ProtectedCustomersCustomerIdRouteWithChildren
  ProtectedCustomersNewRoute: typeof ProtectedCustomersNewRoute
  ProtectedCustomersIndexRoute: typeof ProtectedCustomersIndexRoute
}

const ProtectedCustomersRouteChildren: ProtectedCustomersRouteChildren = {
  ProtectedCustomersCustomerIdRoute:
    ProtectedCustomersCustomerIdRouteWithChildren,
  ProtectedCustomersNewRoute: ProtectedCustomersNewRoute,
  ProtectedCustomersIndexRoute: ProtectedCustomersIndexRoute,
}

const ProtectedCustomersRouteWithChildren =
  ProtectedCustomersRoute._addFileChildren(ProtectedCustomersRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedCustomersRoute: typeof ProtectedCustomersRouteWithChildren
  ProtectedConfiguratorCustomerIdRoute: typeof ProtectedConfiguratorCustomerIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedCustomersRoute: ProtectedCustomersRouteWithChildren,
  ProtectedConfiguratorCustomerIdRoute: ProtectedConfiguratorCustomerIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
